In [74]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [75]:
PROJECT_DIR = r"D:\JMM_Technologies\Cryptocurrency_Forecasting\data\processed_data"

In [76]:
def get_data(name):
	file_name = f"{name}.csv"
	file_path = os.path.join(PROJECT_DIR, file_name)
	return pd.read_csv(file_path)

# Trainig linear_regression on bitcoin

In [77]:
df = get_data("bitcoin_processed")

In [78]:
df.head()

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
0,2024-12-11 14:00:00,98736.86,99539.29,98369.82,99515.98,2230.19310,2024-12-11 14:59:59.999,2.207489e+08,556809,1116.82926,1.105660e+08
1,2024-12-11 15:00:00,99515.99,100800.00,99414.72,100361.64,5764.60580,2024-12-11 15:59:59.999,5.773048e+08,837830,3280.37513,3.284428e+08
2,2024-12-11 16:00:00,100361.64,101090.90,100295.61,100575.99,2950.52479,2024-12-11 16:59:59.999,2.970279e+08,555241,1585.59782,1.596495e+08
3,2024-12-11 17:00:00,100576.00,100982.07,99660.15,99781.90,2298.27737,2024-12-11 17:59:59.999,2.307650e+08,452276,1020.62800,1.024585e+08
4,2024-12-11 18:00:00,99781.89,100786.30,99608.23,100388.71,2207.59419,2024-12-11 18:59:59.999,2.213030e+08,472723,1125.00115,1.127619e+08

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   timestamp                     1000 non-null   object
 1   open                          1000 non-null   float64
 2   high                          1000 non-null   float64
 3   low                           1000 non-null   float64
 4   close                         1000 non-null   float64
 5   volume                        1000 non-null   float64
 6   close_time                    1000 non-null   object
 7   quote_asset_volume            1000 non-null   float64
 8   number_of_trades              1000 non-null   int64
 9   taker_buy_base_asset_volume   1000 non-null   float64
 10  taker_buy_quote_asset_volume  1000 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 86.1+ KB

In [80]:
df = df.drop(columns=['timestamp', 'close_time'])

In [81]:
df.head()

,open,high,low,close,volume,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume
0,98736.86,99539.29,98369.82,99515.98,2230.19310,2.207489e+08,556809,1116.82926,1.105660e+08
1,99515.99,100800.00,99414.72,100361.64,5764.60580,5.773048e+08,837830,3280.37513,3.284428e+08
2,100361.64,101090.90,100295.61,100575.99,2950.52479,2.970279e+08,555241,1585.59782,1.596495e+08
3,100576.00,100982.07,99660.15,99781.90,2298.27737,2.307650e+08,452276,1020.62800,1.024585e+08
4,99781.89,100786.30,99608.23,100388.71,2207.59419,2.213030e+08,472723,1125.00115,1.127619e+08

In [82]:
X = df.drop(columns=['close'], axis=1)

y = df['close']

In [83]:
X.shape

(1000, 8)

In [84]:
y.shape

(1000,)

# Building a base line model

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [86]:
X_train.shape, X_test.shape

((800, 8), (200, 8))

# Scaling the data

In [87]:
scaler = StandardScaler()

In [88]:
X_train = scaler.fit_transform(X_train)
y_train = scaler.fit_transform(y_train.values.reshape(-1,1))

X_test = scaler.fit_transform(X_test)
y_test = scaler.fit_transform(y_test.values.reshape(-1,1))

In [89]:
lr = LinearRegression()

In [90]:
lr.fit(X_train, y_train)

LinearRegression()

In [91]:
y_pred = lr.predict(X_test)

In [92]:
mean_squared_error(y_test, y_pred)

0.003358419189257744

In [93]:
mean_absolute_error(y_test, y_pred)

0.04093797107794251

In [94]:
r2_score(y_test, y_pred)

0.9966415808107423

# Training Linear_Regression on Ethereum

In [105]:
PROJECT_DIR = r"D:\JMM_Technologies\Cryptocurrency_Forecasting\data\processed_data"

In [106]:
def get_data(name):
	file_name = f"{name}.csv"
	file_path = os.path.join(PROJECT_DIR, file_name)
	return pd.read_csv(file_path)

In [107]:
df1 = get_data('ethereum_processed')

In [108]:
df1 = df1.drop(columns=['timestamp', 'close_time'])

In [109]:
X = df1.drop(columns=['close'], axis=1)

y = df1['close']

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [111]:
scaler = StandardScaler()

In [112]:
X_train = scaler.fit_transform(X_train)
y_train = scaler.fit_transform(y_train.values.reshape(-1,1))

X_test = scaler.fit_transform(X_test)
y_test = scaler.fit_transform(y_test.values.reshape(-1,1))

In [113]:
lr = LinearRegression()

In [114]:
lr.fit(X_train, y_train)

LinearRegression()

In [115]:
y_pred = lr.predict(X_test)

In [116]:
mean_squared_error(y_test, y_pred)

0.0018133651291780285

In [117]:
mean_absolute_error(y_test, y_pred)

0.032379076151636

In [118]:
r2_score(y_test, y_pred)

0.9981866348708219

In [120]:
train_predictions = lr.predict(X_train)
train_error = mean_squared_error(y_train, train_predictions)

test_predictions = lr.predict(X_test)
test_error = mean_squared_error(y_test, test_predictions)

print(f"Train Error: {train_error}")
print(f"Test Error: {test_error}")

Train Error: 0.0018450234685083943
Test Error: 0.0018133651291780285